// Use the naming convension:
// "<HTTP-REQUEST-TYPE>_<INTENDED-OBJECT-TO-CRUD>_"
// followed by "REQUEST", "SUCCESS" or "FAILURE"

// A saga will be setup to listen for the "REQUEST"
// The saga will then trigger either a "SUCCESS" or "FAILURE" action.

var reduxActions = {
    // LoginPage actions...
    POST_LOGIN_REQUEST: 'POST_LOGIN_REQUEST',
    POST_LOGIN_SUCCESS: 'POST_LOGIN_SUCCESS',
    POST_LOGIN_FAILURE: 'POST_LOGIN_FAILURE',

    POST_NEW_USER_REQUEST: 'POST_NEW_USER_REQUEST',
    POST_NEW_USER_SUCCESS: 'POST_NEW_USER_SUCCESS',
    POST_NEW_USER_FAILURE: 'POST_NEW_USER_FAILURE',

    LOGOUT: 'LOGOUT',

    // MainHeader actions...

    // HomePage actions...
    GET_PLAY_REQUEST: 'GET_PLAY_REQUEST',
    GET_PLAY_SUCCESS: 'GET_PLAY_SUCCESS',
    GET_PLAY_FAILURE: 'GET_PLAY_FAILURE',

    GET_ACT_REQUEST: 'GET_ACT_REQUEST',
    GET_ACT_SUCCESS: 'GET_ACT_SUCCESS',
    GET_ACT_FAILURE: 'GET_ACT_FAILURE',

    GET_SCENE_REQUEST: 'GET_SCENE_REQUEST',
    GET_SCENE_SUCCESS: 'GET_SCENE_SUCCESS',
    GET_SCENE_FAILURE: 'GET_SCENE_FAILURE',

    GET_LINE_REQUEST: 'GET_LINE_REQUEST',
    GET_LINE_SUCCESS: 'GET_LINE_SUCCESS',
    GET_LINE_FAILURE: 'GET_LINE_FAILURE'
};

export default reduxActions;
